const type = {
    SET_CATEGORY_ID: 'SET_CATEGORY_ID',
    GET_CATEGORIES: 'GET_CATEGORIES',
    ADD_CATEGORY: 'ADD_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
};

export default type;
